import time

import streamlit as st

from langchain_ollama import ChatOllama

from rag_watercan import load_documents, build_vector_store


@st.cache_resource
def get_vector_store():
    chunks = load_documents()
    vector_store = build_vector_store(chunks)
    return vector_store


@st.cache_resource
def get_llm():
    # Uses the local Ollama server; assumes `ollama run qwen2.5:3b` has been pulled/available.
    return ChatOllama(model="qwen2.5:3b", temperature=0.1)


def get_single_answer(question: str) -> tuple[str, list[str]]:
    vector_store = get_vector_store()
    llm = get_llm()

    docs_and_scores = vector_store.similarity_search_with_score(question, k=4)

    if not docs_and_scores:
        return (
            "I could not find information about that in the watercan delivery documents.",
            [],
        )

    # scores are distances: lower = more similar
    best_doc, best_score = docs_and_scores[0]

    # If distance is too high, treat it as 'no relevant answer'.
    # 1.8 is a bit more lenient so short queries like "refund policy"
    # still match the correct section.
    if best_score > 1.8:
        return (
            "I could not find a clearly relevant answer in the watercan delivery documents for this question.",
            [],
        )

    docs = [doc for doc, _ in docs_and_scores]
    context_text = "\n\n".join(doc.page_content for doc in docs)

    prompt = (
        "You are an assistant for a WaterCan delivery service.\n"
        "Use the following context from internal documentation to answer the user's question.\n"
        "If the answer is not clearly present in the context, say you don't know.\n\n"
        f"Context:\n{context_text}\n\n"
        f"Question:\n{question}\n\n"
        "Answer in 2–4 concise sentences."
    )

    response = llm.invoke(prompt)
    answer = getattr(response, "content", str(response)).strip()

    sources = [doc.page_content for doc in docs]

    return answer, sources


def main():
    st.set_page_config(page_title="WaterCan Delivery RAG", page_icon="💧")
    st.title("WaterCan Delivery RAG Assistant (Qwen + Ollama)")
    st.write(
        "Chat about the WaterCan delivery system. "
        "Each answer is generated by a local Qwen model using retrieved documentation as context, "
        "and the time to answer is measured."
    )

    if "messages" not in st.session_state:
        st.session_state["messages"] = []

    # Show conversation history
    for msg in st.session_state["messages"]:
        with st.chat_message(msg["role"]):
            st.markdown(msg["content"])
            if msg.get("latency") is not None:
                st.caption(f"Took {msg['latency']:.2f} seconds")

    # Chat input for new question
    user_input = st.chat_input("Ask something about WaterCan delivery...")

    if user_input:
        # Add user message to history
        st.session_state["messages"].append(
            {"role": "user", "content": user_input, "latency": None}
        )
        with st.chat_message("user"):
            st.markdown(user_input)

        # Generate answer with timing
        with st.chat_message("assistant"):
            with st.spinner("Retrieving context and asking Qwen..."):
                start = time.perf_counter()
                answer, sources = get_single_answer(user_input.strip())
                elapsed = time.perf_counter() - start

                st.markdown(answer)
                st.caption(f"Took {elapsed:.2f} seconds")

                if sources:
                    with st.expander("Show retrieved snippets (context)"):
                        for i, src in enumerate(sources, start=1):
                            st.markdown(f"**Snippet {i}:**")
                            st.write(src)
                            st.markdown("---")

        # Save assistant message with latency
        st.session_state["messages"].append(
            {"role": "assistant", "content": answer, "latency": elapsed}
        )


if __name__ == "__main__":
    main()

